<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\EfCoreContext\EfCoreContext.csproj" />
        <ProjectReference Include="..\SandboxAspireServiceDefaults\SandboxAspireServiceDefaults.csproj" />
        <ProjectReference Include="..\SandboxAuthentication\SandboxAuthentication.csproj" />
        <ProjectReference Include="..\SandboxConfigurations\SandboxConfigurations.csproj" />
        <ProjectReference Include="..\SandboxRemoteApisInterfaces\SandboxRemoteApisInterfaces.csproj" />
        <ProjectReference Include="..\SandboxRemoteApisRepositories\SandboxRemoteApisRepositories.csproj" />
        <ProjectReference Include="..\SandboxServices\SandboxServices.csproj" />
        <ProjectReference Include="..\WebApiSandboxControllers\WebApiSandboxControllers.csproj" />
        <ProjectReference Include="..\WebApiSandboxRepositories\WebApiSandboxRepositories.csproj" />
    </ItemGroup>

</Project>
