<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.3.1" />
        <PackageReference Include="Aspire.StackExchange.Redis" Version="9.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\WeatherDbContext\WeatherDbContext.csproj" />
        <ProjectReference Include="..\SandboxAspireServiceDefaults\SandboxAspireServiceDefaults.csproj" />
        <ProjectReference Include="..\SandboxConfigurations\SandboxConfigurations.csproj" />
        <ProjectReference Include="..\SandboxRemoteApisImportersInterfaces\SandboxRemoteApisImportersInterfaces.csproj" />
        <ProjectReference Include="..\SandboxRemoteApisImporters\SandboxRemoteApisImporters.csproj" />
        <ProjectReference Include="..\SandboxServices\SandboxServices.csproj" />
        <ProjectReference Include="..\WeatherImportConfigs\WeatherImportConfigs.csproj" />
        <ProjectReference Include="..\WebApiSandboxControllers\WebApiSandboxControllers.csproj" />
        <ProjectReference Include="..\WebApiSandboxRepositories\WebApiSandboxRepositories.csproj" />
    </ItemGroup>

</Project>
