<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthContextEfCore\AuthContextEfCore.csproj" />
      <ProjectReference Include="..\AuthViewModels\AuthViewModels.csproj" />
      <ProjectReference Include="..\SandboxAspireServiceDefaults\SandboxAspireServiceDefaults.csproj" />
      <ProjectReference Include="..\SandboxAuthenticationInterfaces\SandboxAuthenticationInterfaces.csproj" />
      <ProjectReference Include="..\SandboxAuthentication\SandboxAuthentication.csproj" />
    </ItemGroup>

</Project>
